using System;


namespace CompiladorForm.Transversal
{
	public enum Categoria
	{
		IDENTIFICADOR, IGUAL_QUE, NUMERO_ENTERO, PARENTESIS_ABRE, PARENTESIS_CIERRA, NUMERO_DECIMAL, SUMA, RESTA, MULTIPLICACION, DIVISION, MODULO, PALABRA_RESERVADA_A, PALABRA_RESERVADA_B, PALABRA_RESERVADA_C, FIN_ARCHIVO

	}
}
