using System;


namespace CompiladorForm.Transversal
{
	public class enum Categoria
	{
		IDENTIFICADOR, NUMERO_ENTERO, NUMERO_DECIMAL, SUMA, RETA, MULTIPLICACION, DIVISION, MODULO, PALABRA_RESERVADA_A, PALABRA_RESERVADA_B, PALABRA_RESERVADA_C, FIN_ARCHIVO

	}
}
