using System;


namespace CompiladorForm.Transversal
{
	public enum Categoria
	{

        ERROR, 


        LETRA_A,LETRA_B, LETRA_C,LETRA_D,LETRA_E,LETRA_F,LETRA_G,LETRA_H,LETRA_I,LETRA_J, LETRA_K, LETRA_L,LETRA_M,LETRA_N,LETRA_O,LETRA_P,
        LETRA_Q,LETRA_R,LETRA_S,LETRA_T,LETRA_U,LETRA_V,LETRA_W,LETRA_X,LETRA_Y,LETRA_Z,ACENTO_A,ACENTO_E,ENIE,ACENTO_O,

        NUMERO_1,NUMERO_2,NUMERO_3,NUMERO_4,NUMERO_5,NUMERO_6,NUMERO_7,NUMERO_8,NUMERO_9,NUMERO_0,

        PUNTO, COMA, PREGUNTA_CIERRA,COMILLA_SIMPLE,ADMIRACION_CIERRA,SLASH,PARENTESIS_ABRE,PARENTESIS_CIERRA, AND,DOS_PUNTOS,PUNTO_COMA,IGUAL,MAS,GUION,GUION_BAJO,
        COMILLA_DOBLE,SIGNO_PESOS,ARROBA,PREGUNTA_ENTRA,ADMIRACION_ABRE, ESPACIO,


        IDENTIFICADOR, IGUAL_QUE, NUMERO_ENTERO, NUMERO_DECIMAL, SUMA, RESTA, MULTIPLICACION, DIVISION, MODULO, PALABRA_RESERVADA_A, PALABRA_RESERVADA_B, PALABRA_RESERVADA_C, FIN_ARCHIVO,
        MENOR_IGUAL_QUE,
        DIFERENTE_QUE,
        MENOR_QUE,
        MAYOR_IGUAL_QUE,
        MAYOR_QUE,
        ASIGNACION,
        LETRA,
        NUMERO,
        ACENTO,
        CARACTER,
        CADENA_LETRA,
        CADENA_NUMERO,
        CADENA_ACENTO,
        CADENA_CARACTER,
        ESPACIO_BLANCO,
        MORSE
    }
}
